name: 'J & J'
favicon: null
layout_spectrum: 0.6954867022577673
typography_spectrum: 0.5161187818739563
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.13189924298785627
  lightness: 0.2972986395470798
  saturation: 0.36189485574141145
  rhythmicContrast: 0.9482099714223295
purpose: []
